
import { useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/hooks/useAuth';
import { 
  Target, 
  CheckCircle, 
  BarChart, 
  Sparkles, 
  ArrowRight, 
  Calendar, 
  Brain
} from 'lucide-react';

const Landing = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  
  useEffect(() => {
    // If user is already logged in, redirect to dashboard
    if (user) {
      navigate('/');
    }
  }, [user, navigate]);
  
  return (
    <div className="flex flex-col min-h-screen bg-background">
      {/* Hero Section */}
      <header className="container mx-auto px-4 py-6 flex justify-between items-center">
        <div className="text-xl font-semibold tracking-tight">
          Achiverr
        </div>
        <div className="flex items-center gap-4">
          <Link to="/pricing" className="text-sm font-medium hover:text-primary">
            Pricing
          </Link>
          <Button asChild variant="outline" size="sm">
            <Link to="/dashboard">Dashboard</Link>
          </Button>
          <Button asChild variant="outline" size="sm">
            <Link to="/login">Sign In</Link>
          </Button>
        </div>
      </header>
      
      <section className="bg-gradient-to-b from-background to-secondary/20 py-20">
        <div className="container mx-auto px-4 text-center">
          <div className="max-w-3xl mx-auto space-y-6">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight">
              Set Goals. Get Roadmaps.
              <span className="block text-accent"> Achieve Success.</span>
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto">
              DreamPlan helps you turn your dreams into actionable plans with AI-powered roadmaps and daily tasks tailored to your goals.
            </p>
            <div className="pt-4 flex flex-col sm:flex-row gap-4 justify-center">
              <Button asChild size="lg" className="gap-2">
                <Link to="/login">
                  Get Started <ArrowRight className="h-4 w-4" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg">
                <Link to="/pricing">View Pricing</Link>
              </Button>
            </div>
          </div>
          
          <div className="mt-16 p-4 bg-card border rounded-lg shadow-lg max-w-4xl mx-auto">
            <div className="aspect-video rounded-md overflow-hidden bg-gradient-to-br from-accent/20 to-secondary flex items-center justify-center">
              <div className="text-center p-8 glass rounded-xl">
                <Sparkles className="h-12 w-12 mx-auto mb-4 text-accent" />
                <h3 className="text-xl font-medium">Smart Goal Planning Demo</h3>
                <p className="text-muted-foreground mt-2">Interactive preview coming soon</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold tracking-tight">
              Turn Your Dreams Into Reality
            </h2>
            <p className="text-muted-foreground mt-4 max-w-2xl mx-auto">
              DreamPlan's AI-powered platform breaks down your goals into achievable steps
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-card border rounded-lg p-6 transition-all hover:shadow-md">
              <Target className="h-10 w-10 text-accent mb-4" />
              <h3 className="text-xl font-medium mb-2">Goal Setting</h3>
              <p className="text-muted-foreground">
                Define clear objectives with customizable timeframes that fit your unique aspirations
              </p>
            </div>
            
            <div className="bg-card border rounded-lg p-6 transition-all hover:shadow-md">
              <Brain className="h-10 w-10 text-accent mb-4" />
              <h3 className="text-xl font-medium mb-2">AI Roadmaps</h3>
              <p className="text-muted-foreground">
                Get personalized action plans generated by advanced AI to guide your journey
              </p>
            </div>
            
            <div className="bg-card border rounded-lg p-6 transition-all hover:shadow-md">
              <Calendar className="h-10 w-10 text-accent mb-4" />
              <h3 className="text-xl font-medium mb-2">Daily Tasks</h3>
              <p className="text-muted-foreground">
                Track progress with adaptive daily task lists that adjust to your pace
              </p>
            </div>
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="py-20 bg-secondary/30">
        <div className="container mx-auto px-4 text-center">
          <div className="max-w-2xl mx-auto">
            <h2 className="text-3xl font-bold tracking-tight mb-4">
              Ready to Achieve Your Goals?
            </h2>
            <p className="text-muted-foreground mb-8">
              Join thousands of successful goal-achievers today
            </p>
            <Button asChild size="lg">
              <Link to="/login">Start Your Journey</Link>
            </Button>
          </div>
        </div>
      </section>
      
      {/* Footer */}
      <footer className="py-12 bg-muted/20">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="text-xl font-semibold mb-4 md:mb-0">
              Achiverr
            </div>
            <div className="flex gap-8 text-sm text-muted-foreground">
              <Link to="/pricing" className="hover:text-foreground">
                Pricing
              </Link>
              <a href="#" className="hover:text-foreground">
                Terms
              </a>
              <a href="#" className="hover:text-foreground">
                Privacy
              </a>
            </div>
          </div>
          <div className="mt-8 text-center text-sm text-muted-foreground">
            © {new Date().getFullYear()} Achiverr. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
